language: node_js
dist: focal
node_js:
- '20'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # Token to access Cozy Registry, you should replace it with a token specific to this konnector
  - secure: sto2CXkrfCwWUyhZByoQQ14hVnKlYzqo+KxaTxbC8SbXbWeDQLX/T2VTKtfffH+BFDsI8GQrCPGTtwxRPzHy5KJh7mPV5w1042EJrkH/lK62iUssxF6oQrLwOeGVLSX8p2Q7jEEngpnwPEYjfVlO96b7BavZ0x+e2ygRRkkrTaxiDiMY4oMK7fM2kZCvEbFYJuTdkbl2a6lV/rT3mSDO+yDPLg4qH/FxDD8A58hThFJOd5XtHXOH0UDdh0DyPNdtnFoDnSUUK6oUIMXM3pILD2MKXnXmYSJknYm7UN7k/QX1kB/XSdaaBiS2oTQkVTiWQyv4mXT/CU+hsXwGmm7OpUHlO5jH4Ev/7+V3uhsTIOUEKZipEv3u8+5Bgf0KJGbgGn+OASCJnhCX2YIN0q1RNo0B6/FwCGAyzQf1geX0RLYtNbVwUGXGYsxd92i+kvIbHzNR8vtQi5ggK1rW4LI932v8B9JJnwHkDDU2VlTjdlIEZZGO2e1qZ6LmdXNQaqoH9s0gt6ZdEh5Cbi9Tepi6ka/vAz41oSiEgLcvOAuHTZoVWre57+dyYMZuaYR9OUvTzvEAB58rxMeBZ9KsepzDeH5siRSTf+zeHZczbdUX7uL9X3avjINIKZETNqr3S2nsgJqCKhHhdBT+iZUbwSgesJS+Hu5FPiuqKpy+ldzYsCA=
  # MATTERMOST_HOOK_URL
  - secure: TPkjpgPMGthLgaXHR/9WP/kmqCU6zNj6w/iy7XYrwf+IcRrdNPgHdTsMuItNkWxIXmJCwZefIYnpDx8M5QzXGFb4WPav/+AAotrTIjezHgBCcckniXVXyV21LtywmyG0yDh1fA15uuCCqXhXGeoyUIC2/6GN0veb8KbGzu07e2+Scfb/IMnc54xCz9H0iryH3O6phL7TwnfjhI4bXZillH6+ongw8eyI+4ekpcHQu8GyyyYP64gQxVqrW4CWQPXIuCx0EP0sQmdoUj9lY14M4fbSjEWk0kSHPZci98KRR2KLD7Jx+NwKcp6KJR3nOgMRMFflgp7QVHZwqsKvQwVSMFPAWjIAvi2JeF5ro1Qd8cPGkHGxY4MAvctUrOU6eHktQWMPB72jWpx9rrU7LPIiUUVMMA+tKCZ5FmEegjJsB4LRWfnYBIt0VZY4mrHFg8szoNzX/l37ecBEmpepfA2GUt/EPg5XpsJgDYEpDUHT9TlW3Zn+StskRP4+496eh7TeuQlKRRt9EbtL+QVKR5Er8cAF9iI6V9Ebb4Fr7r4G2Qwu7KhfR+ry6hRUSzcAhQ5POzvjzVyGibEpF8jxpkr0ybilvz6S9viAkTBwng1oSxDpiGoozWcfiKzrs7EGYJphdS5wb7zyMn0PFanqZRfLpg6AsVBr6YcLdT/IxHX9gMA=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
